#! /usr/bin/env bash
echo "== CREATING BUCKET =="
# This script creates a bucket in the specified region
if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

if [ -z "$2" ]; then
   aws s3api create-bucket --bucket $1 \
   --query Location \
   --output text
else
aws s3api create-bucket --bucket $1 \
--create-bucket-configuration="LocationConstraint=$2" \
--query Location
--output text
fi
