#! /usr/bin/env bash
set -e

echo "== SYNCING OBJECTS =="

if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

if [ -z "$2" ]; then
    echo "Check for filename prefix "
    exit 1
fi
OUTPUT_DIR="/tmp/s3-bash-scripts"
FILENAME_PREFIX=$2
BUCKET_NAME=$1
mkdir -p $OUTPUT_DIR

rm -rf $OUTPUT_DIR/*
NUM_FILES=$(( RANDOM % 6 + 5 ))

for((i=1;i<=10;i++)); do
    random_filename="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    dd if=/dev/urandom of=$random_filename bs=1M count=1
done

tree $OUTPUT_DIR


aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files
